name: publish

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.0
        bundler-cache: true
    - name: set credentials
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        echo ":github: Bearer ${PUBLISH_TOKEN}" >> ~/.gem/credentials
      env:
        PUBLISH_TOKEN: ${{secrets.PUBLISH_TOKEN}}
    - name: publish
      run: |
        gem build phantom.gemspec --output phantom.gem
        gem push --key github --host https://rubygems.pkg.github.com/vivekmiyani phantom.gem
